import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import { Tomorrow } from 'next/font/google';
import './globals.css';

const tommorow = Tomorrow({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Filipino Web Development Peers',
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: '/fwdpIcon.png',
      type: 'image/png',
    },
    shortcut: { url: '/fwdpIcon.png', type: 'image/png' },
  },
};

type childrenProps = { children: React.ReactNode };

export default function RootLayout({ children }: childrenProps) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='./fwdpIcon.png' sizes='any' />
      </head>
      <body className={tommorow.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
