import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Filipino Web Development Peers',
	description: 'Generated by create next app',
	icons: {
		icon: {
			url: '/fwdpIcon.png',
			type: 'image/png',
		},
		shortcut: { url: '/fwdpIcon.png', type: 'image/png' },
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<link
					rel="icon"
					href="./fwdpIcon.png"
					sizes="any"
				/>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
