import type { Metadata } from 'next';
import { Tomorrow } from 'next/font/google';
import './globals.css';

import Navbar from '@/components/Navbar';
import ScrollToTopButton from '@/components/ScrollToTopButton';
import { childrenProps } from '@/globalTypes';

const tommorow = Tomorrow({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Filipino Web Development Peers',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
  icons: {
    icon: {
      url: '/fwdpIcon.png',
      type: 'image/png',
    },
    shortcut: { url: '/fwdpIcon.png', type: 'image/png' },
  },
  themeColor: '#f5e6e0',
};

export default function RootLayout({ children }: childrenProps) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./fwdpIcon.png" sizes="any" />
      </head>
      <body className={tommorow.className}>
        <Navbar />
        <ScrollToTopButton />
        {children}
      </body>
    </html>
  );
}
